on: [push]

name: build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build release
        run: |
          docker run --rm -v "$(pwd)":/home/rust/src messense/rust-musl-cross:aarch64-musl \
            cargo build --release

